# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import moralis_streams_api
from moralis_streams_api.api.history_api import HistoryApi  # noqa: E501
from moralis_streams_api.rest import ApiException


class TestHistoryApi(unittest.TestCase):
    """HistoryApi unit test stubs"""

    def setUp(self):
        self.api = HistoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_history(self):
        """Test case for get_history

        """
        pass

    def test_replay_history(self):
        """Test case for replay_history

        """
        pass


if __name__ == '__main__':
    unittest.main()
