# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import moralis_streams_api
from moralis_streams_api.api.beta_api import BetaApi  # noqa: E501
from moralis_streams_api.rest import ApiException


class TestBetaApi(unittest.TestCase):
    """BetaApi unit test stubs"""

    def setUp(self):
        self.api = BetaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_stats(self):
        """Test case for get_stats

        """
        pass


if __name__ == '__main__':
    unittest.main()
