# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import moralis_streams_api
from moralis_streams_api.api.evm_streams_api import EVMStreamsApi  # noqa: E501
from moralis_streams_api.rest import ApiException


class TestEVMStreamsApi(unittest.TestCase):
    """EVMStreamsApi unit test stubs"""

    def setUp(self):
        self.api = EVMStreamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_address_to_stream(self):
        """Test case for add_address_to_stream

        """
        pass

    def test_create_stream(self):
        """Test case for create_stream

        """
        pass

    def test_delete_address_from_stream(self):
        """Test case for delete_address_from_stream

        """
        pass

    def test_delete_stream(self):
        """Test case for delete_stream

        """
        pass

    def test_get_addresses(self):
        """Test case for get_addresses

        """
        pass

    def test_get_stream(self):
        """Test case for get_stream

        """
        pass

    def test_get_streams(self):
        """Test case for get_streams

        """
        pass

    def test_update_stream(self):
        """Test case for update_stream

        """
        pass

    def test_update_stream_status(self):
        """Test case for update_stream_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
