# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import moralis_streams_api
from moralis_streams_api.models.webhook_types_i_webhook import WebhookTypesIWebhook  # noqa: E501
from moralis_streams_api.rest import ApiException


class TestWebhookTypesIWebhook(unittest.TestCase):
    """WebhookTypesIWebhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebhookTypesIWebhook(self):
        """Test WebhookTypesIWebhook"""
        # FIXME: construct object with mandatory attributes with example values
        # model = moralis_streams_api.models.webhook_types_i_webhook.WebhookTypesIWebhook()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
