# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import moralis_streams_api
from moralis_streams_api.models.settings_types_settings_model import SettingsTypesSettingsModel  # noqa: E501
from moralis_streams_api.rest import ApiException


class TestSettingsTypesSettingsModel(unittest.TestCase):
    """SettingsTypesSettingsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSettingsTypesSettingsModel(self):
        """Test SettingsTypesSettingsModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = moralis_streams_api.models.settings_types_settings_model.SettingsTypesSettingsModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
