# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import moralis_streams_api
from moralis_streams_api.models.addresses_types_address_response import AddressesTypesAddressResponse  # noqa: E501
from moralis_streams_api.rest import ApiException


class TestAddressesTypesAddressResponse(unittest.TestCase):
    """AddressesTypesAddressResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressesTypesAddressResponse(self):
        """Test AddressesTypesAddressResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = moralis_streams_api.models.addresses_types_address_response.AddressesTypesAddressResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
