# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import moralis_streams_api
from moralis_streams_api.models.streams_abi import StreamsAbi  # noqa: E501
from moralis_streams_api.rest import ApiException


class TestStreamsAbi(unittest.TestCase):
    """StreamsAbi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreamsAbi(self):
        """Test StreamsAbi"""
        # FIXME: construct object with mandatory attributes with example values
        # model = moralis_streams_api.models.streams_abi.StreamsAbi()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
