# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import moralis_streams_api
from moralis_streams_api.models.abi_type import AbiType  # noqa: E501
from moralis_streams_api.rest import ApiException


class TestAbiType(unittest.TestCase):
    """AbiType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAbiType(self):
        """Test AbiType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = moralis_streams_api.models.abi_type.AbiType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
