# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import moralis_streams_api
from moralis_streams_api.models.all_ofstreams_types_streams_model_create_abi import AllOfstreamsTypesStreamsModelCreateAbi  # noqa: E501
from moralis_streams_api.rest import ApiException


class TestAllOfstreamsTypesStreamsModelCreateAbi(unittest.TestCase):
    """AllOfstreamsTypesStreamsModelCreateAbi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfstreamsTypesStreamsModelCreateAbi(self):
        """Test AllOfstreamsTypesStreamsModelCreateAbi"""
        # FIXME: construct object with mandatory attributes with example values
        # model = moralis_streams_api.models.all_ofstreams_types_streams_model_create_abi.AllOfstreamsTypesStreamsModelCreateAbi()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
