# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AbiInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'indexed': 'bool',
        'components': 'list[AbiInput]',
        'internal_type': 'str'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'indexed': 'indexed',
        'components': 'components',
        'internal_type': 'internalType'
    }

    def __init__(self, name=None, type=None, indexed=None, components=None, internal_type=None):  # noqa: E501
        """AbiInput - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._type = None
        self._indexed = None
        self._components = None
        self._internal_type = None
        self.discriminator = None
        self.name = name
        self.type = type
        if indexed is not None:
            self.indexed = indexed
        if components is not None:
            self.components = components
        if internal_type is not None:
            self.internal_type = internal_type

    @property
    def name(self):
        """Gets the name of this AbiInput.  # noqa: E501


        :return: The name of this AbiInput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AbiInput.


        :param name: The name of this AbiInput.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self):
        """Gets the type of this AbiInput.  # noqa: E501


        :return: The type of this AbiInput.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AbiInput.


        :param type: The type of this AbiInput.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def indexed(self):
        """Gets the indexed of this AbiInput.  # noqa: E501


        :return: The indexed of this AbiInput.  # noqa: E501
        :rtype: bool
        """
        return self._indexed

    @indexed.setter
    def indexed(self, indexed):
        """Sets the indexed of this AbiInput.


        :param indexed: The indexed of this AbiInput.  # noqa: E501
        :type: bool
        """

        self._indexed = indexed

    @property
    def components(self):
        """Gets the components of this AbiInput.  # noqa: E501


        :return: The components of this AbiInput.  # noqa: E501
        :rtype: list[AbiInput]
        """
        return self._components

    @components.setter
    def components(self, components):
        """Sets the components of this AbiInput.


        :param components: The components of this AbiInput.  # noqa: E501
        :type: list[AbiInput]
        """

        self._components = components

    @property
    def internal_type(self):
        """Gets the internal_type of this AbiInput.  # noqa: E501


        :return: The internal_type of this AbiInput.  # noqa: E501
        :rtype: str
        """
        return self._internal_type

    @internal_type.setter
    def internal_type(self, internal_type):
        """Sets the internal_type of this AbiInput.


        :param internal_type: The internal_type of this AbiInput.  # noqa: E501
        :type: str
        """

        self._internal_type = internal_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AbiInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AbiInput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
