# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AdvancedOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'topic0': 'str',
        'filter': 'StreamsFilter',
        'include_native_txs': 'bool'
    }

    attribute_map = {
        'topic0': 'topic0',
        'filter': 'filter',
        'include_native_txs': 'includeNativeTxs'
    }

    def __init__(self, topic0=None, filter=None, include_native_txs=None):  # noqa: E501
        """AdvancedOptions - a model defined in Swagger"""  # noqa: E501
        self._topic0 = None
        self._filter = None
        self._include_native_txs = None
        self.discriminator = None
        self.topic0 = topic0
        if filter is not None:
            self.filter = filter
        if include_native_txs is not None:
            self.include_native_txs = include_native_txs

    @property
    def topic0(self):
        """Gets the topic0 of this AdvancedOptions.  # noqa: E501


        :return: The topic0 of this AdvancedOptions.  # noqa: E501
        :rtype: str
        """
        return self._topic0

    @topic0.setter
    def topic0(self, topic0):
        """Sets the topic0 of this AdvancedOptions.


        :param topic0: The topic0 of this AdvancedOptions.  # noqa: E501
        :type: str
        """
        if topic0 is None:
            raise ValueError("Invalid value for `topic0`, must not be `None`")  # noqa: E501

        self._topic0 = topic0

    @property
    def filter(self):
        """Gets the filter of this AdvancedOptions.  # noqa: E501


        :return: The filter of this AdvancedOptions.  # noqa: E501
        :rtype: StreamsFilter
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """Sets the filter of this AdvancedOptions.


        :param filter: The filter of this AdvancedOptions.  # noqa: E501
        :type: StreamsFilter
        """

        self._filter = filter

    @property
    def include_native_txs(self):
        """Gets the include_native_txs of this AdvancedOptions.  # noqa: E501


        :return: The include_native_txs of this AdvancedOptions.  # noqa: E501
        :rtype: bool
        """
        return self._include_native_txs

    @include_native_txs.setter
    def include_native_txs(self, include_native_txs):
        """Sets the include_native_txs of this AdvancedOptions.


        :param include_native_txs: The include_native_txs of this AdvancedOptions.  # noqa: E501
        :type: bool
        """

        self._include_native_txs = include_native_txs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdvancedOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdvancedOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
