# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class INFTApprovalERC1155(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'transaction_hash': 'str',
        'contract': 'str',
        'log_index': 'str',
        'tag': 'str',
        'account': 'str',
        'operator': 'str',
        'approved': 'bool',
        'token_contract_type': 'str',
        'token_name': 'str',
        'token_symbol': 'str'
    }

    attribute_map = {
        'transaction_hash': 'transactionHash',
        'contract': 'contract',
        'log_index': 'logIndex',
        'tag': 'tag',
        'account': 'account',
        'operator': 'operator',
        'approved': 'approved',
        'token_contract_type': 'tokenContractType',
        'token_name': 'tokenName',
        'token_symbol': 'tokenSymbol'
    }

    def __init__(self, transaction_hash=None, contract=None, log_index=None, tag=None, account=None, operator=None, approved=None, token_contract_type=None, token_name=None, token_symbol=None):  # noqa: E501
        """INFTApprovalERC1155 - a model defined in Swagger"""  # noqa: E501
        self._transaction_hash = None
        self._contract = None
        self._log_index = None
        self._tag = None
        self._account = None
        self._operator = None
        self._approved = None
        self._token_contract_type = None
        self._token_name = None
        self._token_symbol = None
        self.discriminator = None
        self.transaction_hash = transaction_hash
        self.contract = contract
        self.log_index = log_index
        self.tag = tag
        self.account = account
        self.operator = operator
        self.approved = approved
        self.token_contract_type = token_contract_type
        self.token_name = token_name
        self.token_symbol = token_symbol

    @property
    def transaction_hash(self):
        """Gets the transaction_hash of this INFTApprovalERC1155.  # noqa: E501


        :return: The transaction_hash of this INFTApprovalERC1155.  # noqa: E501
        :rtype: str
        """
        return self._transaction_hash

    @transaction_hash.setter
    def transaction_hash(self, transaction_hash):
        """Sets the transaction_hash of this INFTApprovalERC1155.


        :param transaction_hash: The transaction_hash of this INFTApprovalERC1155.  # noqa: E501
        :type: str
        """
        if transaction_hash is None:
            raise ValueError("Invalid value for `transaction_hash`, must not be `None`")  # noqa: E501

        self._transaction_hash = transaction_hash

    @property
    def contract(self):
        """Gets the contract of this INFTApprovalERC1155.  # noqa: E501


        :return: The contract of this INFTApprovalERC1155.  # noqa: E501
        :rtype: str
        """
        return self._contract

    @contract.setter
    def contract(self, contract):
        """Sets the contract of this INFTApprovalERC1155.


        :param contract: The contract of this INFTApprovalERC1155.  # noqa: E501
        :type: str
        """
        if contract is None:
            raise ValueError("Invalid value for `contract`, must not be `None`")  # noqa: E501

        self._contract = contract

    @property
    def log_index(self):
        """Gets the log_index of this INFTApprovalERC1155.  # noqa: E501


        :return: The log_index of this INFTApprovalERC1155.  # noqa: E501
        :rtype: str
        """
        return self._log_index

    @log_index.setter
    def log_index(self, log_index):
        """Sets the log_index of this INFTApprovalERC1155.


        :param log_index: The log_index of this INFTApprovalERC1155.  # noqa: E501
        :type: str
        """
        if log_index is None:
            raise ValueError("Invalid value for `log_index`, must not be `None`")  # noqa: E501

        self._log_index = log_index

    @property
    def tag(self):
        """Gets the tag of this INFTApprovalERC1155.  # noqa: E501


        :return: The tag of this INFTApprovalERC1155.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this INFTApprovalERC1155.


        :param tag: The tag of this INFTApprovalERC1155.  # noqa: E501
        :type: str
        """
        if tag is None:
            raise ValueError("Invalid value for `tag`, must not be `None`")  # noqa: E501

        self._tag = tag

    @property
    def account(self):
        """Gets the account of this INFTApprovalERC1155.  # noqa: E501


        :return: The account of this INFTApprovalERC1155.  # noqa: E501
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this INFTApprovalERC1155.


        :param account: The account of this INFTApprovalERC1155.  # noqa: E501
        :type: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account

    @property
    def operator(self):
        """Gets the operator of this INFTApprovalERC1155.  # noqa: E501


        :return: The operator of this INFTApprovalERC1155.  # noqa: E501
        :rtype: str
        """
        return self._operator

    @operator.setter
    def operator(self, operator):
        """Sets the operator of this INFTApprovalERC1155.


        :param operator: The operator of this INFTApprovalERC1155.  # noqa: E501
        :type: str
        """
        if operator is None:
            raise ValueError("Invalid value for `operator`, must not be `None`")  # noqa: E501

        self._operator = operator

    @property
    def approved(self):
        """Gets the approved of this INFTApprovalERC1155.  # noqa: E501


        :return: The approved of this INFTApprovalERC1155.  # noqa: E501
        :rtype: bool
        """
        return self._approved

    @approved.setter
    def approved(self, approved):
        """Sets the approved of this INFTApprovalERC1155.


        :param approved: The approved of this INFTApprovalERC1155.  # noqa: E501
        :type: bool
        """
        if approved is None:
            raise ValueError("Invalid value for `approved`, must not be `None`")  # noqa: E501

        self._approved = approved

    @property
    def token_contract_type(self):
        """Gets the token_contract_type of this INFTApprovalERC1155.  # noqa: E501


        :return: The token_contract_type of this INFTApprovalERC1155.  # noqa: E501
        :rtype: str
        """
        return self._token_contract_type

    @token_contract_type.setter
    def token_contract_type(self, token_contract_type):
        """Sets the token_contract_type of this INFTApprovalERC1155.


        :param token_contract_type: The token_contract_type of this INFTApprovalERC1155.  # noqa: E501
        :type: str
        """
        if token_contract_type is None:
            raise ValueError("Invalid value for `token_contract_type`, must not be `None`")  # noqa: E501

        self._token_contract_type = token_contract_type

    @property
    def token_name(self):
        """Gets the token_name of this INFTApprovalERC1155.  # noqa: E501


        :return: The token_name of this INFTApprovalERC1155.  # noqa: E501
        :rtype: str
        """
        return self._token_name

    @token_name.setter
    def token_name(self, token_name):
        """Sets the token_name of this INFTApprovalERC1155.


        :param token_name: The token_name of this INFTApprovalERC1155.  # noqa: E501
        :type: str
        """
        if token_name is None:
            raise ValueError("Invalid value for `token_name`, must not be `None`")  # noqa: E501

        self._token_name = token_name

    @property
    def token_symbol(self):
        """Gets the token_symbol of this INFTApprovalERC1155.  # noqa: E501


        :return: The token_symbol of this INFTApprovalERC1155.  # noqa: E501
        :rtype: str
        """
        return self._token_symbol

    @token_symbol.setter
    def token_symbol(self, token_symbol):
        """Sets the token_symbol of this INFTApprovalERC1155.


        :param token_symbol: The token_symbol of this INFTApprovalERC1155.  # noqa: E501
        :type: str
        """
        if token_symbol is None:
            raise ValueError("Invalid value for `token_symbol`, must not be `None`")  # noqa: E501

        self._token_symbol = token_symbol

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(INFTApprovalERC1155, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, INFTApprovalERC1155):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
