# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class INFTApproval(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'erc721': 'list[INFTApprovalERC721]',
        'erc1155': 'list[INFTApprovalERC1155]'
    }

    attribute_map = {
        'erc721': 'ERC721',
        'erc1155': 'ERC1155'
    }

    def __init__(self, erc721=None, erc1155=None):  # noqa: E501
        """INFTApproval - a model defined in Swagger"""  # noqa: E501
        self._erc721 = None
        self._erc1155 = None
        self.discriminator = None
        self.erc721 = erc721
        self.erc1155 = erc1155

    @property
    def erc721(self):
        """Gets the erc721 of this INFTApproval.  # noqa: E501


        :return: The erc721 of this INFTApproval.  # noqa: E501
        :rtype: list[INFTApprovalERC721]
        """
        return self._erc721

    @erc721.setter
    def erc721(self, erc721):
        """Sets the erc721 of this INFTApproval.


        :param erc721: The erc721 of this INFTApproval.  # noqa: E501
        :type: list[INFTApprovalERC721]
        """
        if erc721 is None:
            raise ValueError("Invalid value for `erc721`, must not be `None`")  # noqa: E501

        self._erc721 = erc721

    @property
    def erc1155(self):
        """Gets the erc1155 of this INFTApproval.  # noqa: E501


        :return: The erc1155 of this INFTApproval.  # noqa: E501
        :rtype: list[INFTApprovalERC1155]
        """
        return self._erc1155

    @erc1155.setter
    def erc1155(self, erc1155):
        """Sets the erc1155 of this INFTApproval.


        :param erc1155: The erc1155 of this INFTApproval.  # noqa: E501
        :type: list[INFTApprovalERC1155]
        """
        if erc1155 is None:
            raise ValueError("Invalid value for `erc1155`, must not be `None`")  # noqa: E501

        self._erc1155 = erc1155

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(INFTApproval, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, INFTApproval):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
