# coding: utf-8

"""
    Streams Api

    API that provides access to Moralis Streams  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PartialStreamsTypesStreamsModelCreate_(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'webhook_url': 'str',
        'description': 'str',
        'tag': 'str',
        'token_address': 'str',
        'topic0': 'str',
        'include_native_txs': 'bool',
        'abi': 'AllOfPartialStreamsTypesStreamsModelCreateAbi',
        'filter': 'AllOfPartialStreamsTypesStreamsModelCreateFilter',
        'address': 'str',
        'chain_ids': 'list[str]',
        'type': 'StreamsType'
    }

    attribute_map = {
        'webhook_url': 'webhookUrl',
        'description': 'description',
        'tag': 'tag',
        'token_address': 'tokenAddress',
        'topic0': 'topic0',
        'include_native_txs': 'includeNativeTxs',
        'abi': 'abi',
        'filter': 'filter',
        'address': 'address',
        'chain_ids': 'chainIds',
        'type': 'type'
    }

    def __init__(self, webhook_url=None, description=None, tag=None, token_address=None, topic0=None, include_native_txs=None, abi=None, filter=None, address=None, chain_ids=None, type=None):  # noqa: E501
        """PartialStreamsTypesStreamsModelCreate_ - a model defined in Swagger"""  # noqa: E501
        self._webhook_url = None
        self._description = None
        self._tag = None
        self._token_address = None
        self._topic0 = None
        self._include_native_txs = None
        self._abi = None
        self._filter = None
        self._address = None
        self._chain_ids = None
        self._type = None
        self.discriminator = None
        if webhook_url is not None:
            self.webhook_url = webhook_url
        if description is not None:
            self.description = description
        if tag is not None:
            self.tag = tag
        if token_address is not None:
            self.token_address = token_address
        if topic0 is not None:
            self.topic0 = topic0
        if include_native_txs is not None:
            self.include_native_txs = include_native_txs
        if abi is not None:
            self.abi = abi
        if filter is not None:
            self.filter = filter
        if address is not None:
            self.address = address
        if chain_ids is not None:
            self.chain_ids = chain_ids
        if type is not None:
            self.type = type

    @property
    def webhook_url(self):
        """Gets the webhook_url of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501

        Webhook URL where moralis will send the POST request.  # noqa: E501

        :return: The webhook_url of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :rtype: str
        """
        return self._webhook_url

    @webhook_url.setter
    def webhook_url(self, webhook_url):
        """Sets the webhook_url of this PartialStreamsTypesStreamsModelCreate_.

        Webhook URL where moralis will send the POST request.  # noqa: E501

        :param webhook_url: The webhook_url of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :type: str
        """

        self._webhook_url = webhook_url

    @property
    def description(self):
        """Gets the description of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501

        A description for this stream  # noqa: E501

        :return: The description of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PartialStreamsTypesStreamsModelCreate_.

        A description for this stream  # noqa: E501

        :param description: The description of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def tag(self):
        """Gets the tag of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501

        A user-provided tag that will be send along the webhook, the user can use this tag to identify the specific stream if multiple streams are present  # noqa: E501

        :return: The tag of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this PartialStreamsTypesStreamsModelCreate_.

        A user-provided tag that will be send along the webhook, the user can use this tag to identify the specific stream if multiple streams are present  # noqa: E501

        :param tag: The tag of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :type: str
        """

        self._tag = tag

    @property
    def token_address(self):
        """Gets the token_address of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501

        The token address of the contract, required if the type : log  # noqa: E501

        :return: The token_address of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :rtype: str
        """
        return self._token_address

    @token_address.setter
    def token_address(self, token_address):
        """Sets the token_address of this PartialStreamsTypesStreamsModelCreate_.

        The token address of the contract, required if the type : log  # noqa: E501

        :param token_address: The token_address of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :type: str
        """

        self._token_address = token_address

    @property
    def topic0(self):
        """Gets the topic0 of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501

        The topic0 of the event in hex, required if the type : log  # noqa: E501

        :return: The topic0 of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :rtype: str
        """
        return self._topic0

    @topic0.setter
    def topic0(self, topic0):
        """Sets the topic0 of this PartialStreamsTypesStreamsModelCreate_.

        The topic0 of the event in hex, required if the type : log  # noqa: E501

        :param topic0: The topic0 of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :type: str
        """

        self._topic0 = topic0

    @property
    def include_native_txs(self):
        """Gets the include_native_txs of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501

        Include or not native transactions defaults to false (only applied when type:contract)  # noqa: E501

        :return: The include_native_txs of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :rtype: bool
        """
        return self._include_native_txs

    @include_native_txs.setter
    def include_native_txs(self, include_native_txs):
        """Sets the include_native_txs of this PartialStreamsTypesStreamsModelCreate_.

        Include or not native transactions defaults to false (only applied when type:contract)  # noqa: E501

        :param include_native_txs: The include_native_txs of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :type: bool
        """

        self._include_native_txs = include_native_txs

    @property
    def abi(self):
        """Gets the abi of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501


        :return: The abi of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :rtype: AllOfPartialStreamsTypesStreamsModelCreateAbi
        """
        return self._abi

    @abi.setter
    def abi(self, abi):
        """Sets the abi of this PartialStreamsTypesStreamsModelCreate_.


        :param abi: The abi of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :type: AllOfPartialStreamsTypesStreamsModelCreateAbi
        """

        self._abi = abi

    @property
    def filter(self):
        """Gets the filter of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501


        :return: The filter of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :rtype: AllOfPartialStreamsTypesStreamsModelCreateFilter
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """Sets the filter of this PartialStreamsTypesStreamsModelCreate_.


        :param filter: The filter of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :type: AllOfPartialStreamsTypesStreamsModelCreateFilter
        """

        self._filter = filter

    @property
    def address(self):
        """Gets the address of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501

        The wallet address of the user, required if the type : tx  # noqa: E501

        :return: The address of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this PartialStreamsTypesStreamsModelCreate_.

        The wallet address of the user, required if the type : tx  # noqa: E501

        :param address: The address of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def chain_ids(self):
        """Gets the chain_ids of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501

        The ids of the chains for this stream in hex Ex: [\"0x1\",\"0x38\"]  # noqa: E501

        :return: The chain_ids of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :rtype: list[str]
        """
        return self._chain_ids

    @chain_ids.setter
    def chain_ids(self, chain_ids):
        """Sets the chain_ids of this PartialStreamsTypesStreamsModelCreate_.

        The ids of the chains for this stream in hex Ex: [\"0x1\",\"0x38\"]  # noqa: E501

        :param chain_ids: The chain_ids of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :type: list[str]
        """

        self._chain_ids = chain_ids

    @property
    def type(self):
        """Gets the type of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501


        :return: The type of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :rtype: StreamsType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PartialStreamsTypesStreamsModelCreate_.


        :param type: The type of this PartialStreamsTypesStreamsModelCreate_.  # noqa: E501
        :type: StreamsType
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PartialStreamsTypesStreamsModelCreate_, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PartialStreamsTypesStreamsModelCreate_):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
